---
- hosts: all
  sudo: no

  tasks:
      ##  CVE-2014-6271
      #
      # Sources:
        #           http://seclists.org/oss-sec/2014/q3/650
        #           http://www.troyhunt.com/2014/09/everything-you-need-to-know-about.html
        #           https://access.redhat.com/articles/1200223
        #           https://securityblog.redhat.com/2014/09/24/bash-specially-crafted-environment-variables-code-injection-attack/

    - name: Testing CVE-2014-6271
      shell: env x='() { :;}; echo vulnerable' bash -c "echo this is a test"
      register: cve

    - name: CVE-2014-6271 install exploit.sh
      copy: src=./files/CVE-2014-6271/exploit.sh dest=./exploit-CVE-2014-6271.sh mode=0755

    - name: Run exploit.sh
      ignore_errors: True
      command: ./exploit-CVE-2014-6271.sh

    - stat: path=./echo
      ignore_errors: True
      register: exploit_echo

    - name: Remove test file echo
      ignore_errors: True
      file: path=./echo state=absent

    - name: Remove exploit-CVE-2014-6271.sh
      ignore_errors: True
      file: path=./exploit-CVE-2014-6271.sh state=absent

    - fail: msg="[x] CVE-2014-6271 - FOUNDED!"
      when: cve.stdout.find('vulnerable') != -1

    - fail: msg="[x] CVE-2014-7169 - FOUNDED!"
      when: exploit_echo.stat.exists == True

